### PR TITLE
[B2B3-550] hide empty ad

### PR DESCRIPTION
**Pull request by mtyeh411**

### CODE REVIEW

**Comment by mtyeh411** [comment]
as related to hiding pencil ad on homepage redesign
https://github.com/weddingwire/weddingwire-ng/pull/7655

**Comment by mtyeh411** [comment]
@chancedowns can you take a look?

**Comment by chancedowns** [comment]
Looking at the docs, there are a few options. It looks like you picked the global option instead of per slot, do you think that's the best? I'm not too familiar with it, so I don't know the reasoning behind one vs the other

**Comment by mtyeh411** [comment]
no reasoning really ... i'll look through the docs again

**Comment by mtyeh411** [comment]
closing this ... @americos is working to modify the helper to collapse at the slot level instead of the global level

**Pull request closed without merging**
